### ISSUE TITLE
Vulnerability report

### ISSUE THREAD

**Issue by JafarAkhondali** [freehuntx/godot-matcha#10]
We are a group of researchers from Leiden University, and we conduct research on vulnerabilities in open-source software. We have discovered and verified a high-severity vulnerability in your project(freehuntx/godot-matcha). Explaining the vulnerability further in this issue could allow malicious users to access details, so we recommend [enabling private vulnerability reporting on GitHub](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository) to discuss this matter confidentially.
        After you have enabled this feature, please add a comment to this issue so we can continue our discussion. If you have any questions, feel free to leave a reply here or send an email to: j.akhoundali [at] liacs.leidenuniv.nl

**Comment by freehuntx** [comment]
Enabled.

**Comment by freehuntx** [comment]
Closed as the report is just relevant for the testing file "server.js" which is not intended to be exposed to the internet and just for local development. It can even be removed.
Nevertheless thanks for the report!

**Comment by JafarAkhondali** [comment]
Thanks for verifying @freehuntx 
We now know that the impact is not high, but still it's better to fix the code, as in theory it open a vulnerable port in limited time, and makes the developer's system vulnerable. I do understand that it's not a priority for you, so we'll send a pull request to fix it, so you can simply accept it. Please let me know if you don't want to receive the pull request at all.

**Comment by freehuntx** [comment]
Of course feel free :) I will merge it.
