### ISSUE TITLE
RPC calls not being received 

### ISSUE THREAD

**Issue by ghost** [freehuntx/godot-matcha#8]

**Comment by masterthdev** [comment]
MultiplayerPeer's peer connected signal triggers before MultiplayerAPI one, so you are trying to send a rpc before peer is added to multiplayer api. You need to connect multiplayer.peer_connected signal instead of using MatchaPeer.peer_joined.

**Comment by freehuntx** [comment]
Im currently reworking the library to use mqtt for signaling instead. So this will be fixed after thats done.

**Comment by Catechojab** [comment]
> MultiplayerPeer's peer connected signal triggers before MultiplayerAPI one, so you are trying to send a rpc before peer is added to multiplayer api. You need to connect multiplayer.peer_connected signal instead of using MatchaPeer.peer_joined.

Huh. It sounds so obvious in retrospect, but I guess we all overlook things sometimes. Thanks for the help, it works now.
